// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_XqMC9e4mVJTQkXPAXMr-lp-lFhHcPc',
    appId: '1:509149135649:web:22fdf41aa4a13bb86df460',
    messagingSenderId: '509149135649',
    projectId: 'farmer-app-bbf77',
    authDomain: 'farmer-app-bbf77.firebaseapp.com',
    storageBucket: 'farmer-app-bbf77.firebasestorage.app',
    measurementId: 'G-FPKLP4N10K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbwOGwICiISHVANjCHF_553kDM0z2M48',
    appId: '1:509149135649:android:e99fd90684ec4f2c6df460',
    messagingSenderId: '509149135649',
    projectId: 'farmer-app-bbf77',
    storageBucket: 'farmer-app-bbf77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxxhKD3oMrnNRt7piaiHB4zeBQaCgUho',
    appId: '1:509149135649:ios:ff619df7b943a2e86df460',
    messagingSenderId: '509149135649',
    projectId: 'farmer-app-bbf77',
    storageBucket: 'farmer-app-bbf77.firebasestorage.app',
    androidClientId: '509149135649-2adbna69t4lnf2670n19vup25fd6ulks.apps.googleusercontent.com',
    iosClientId: '509149135649-j06hblkbkd2m7u0872c9mrfv0kd58cmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxxhKD3oMrnNRt7piaiHB4zeBQaCgUho',
    appId: '1:509149135649:ios:ff619df7b943a2e86df460',
    messagingSenderId: '509149135649',
    projectId: 'farmer-app-bbf77',
    storageBucket: 'farmer-app-bbf77.firebasestorage.app',
    androidClientId: '509149135649-2adbna69t4lnf2670n19vup25fd6ulks.apps.googleusercontent.com',
    iosClientId: '509149135649-j06hblkbkd2m7u0872c9mrfv0kd58cmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH_XqMC9e4mVJTQkXPAXMr-lp-lFhHcPc',
    appId: '1:509149135649:web:98b0a9d87a2c0cdd6df460',
    messagingSenderId: '509149135649',
    projectId: 'farmer-app-bbf77',
    authDomain: 'farmer-app-bbf77.firebaseapp.com',
    storageBucket: 'farmer-app-bbf77.firebasestorage.app',
    measurementId: 'G-YXBW4M20HT',
  );
}
